IOT-6649: Migrate kafka to simiango
simiancreative/simiango pull request #12
Opened 2022-02-02 22:20 UTC by jorge-crespo-cedeno

2022-02-02 22:35 UTC, rossnelson requested changes
@jorge-crespo-cedeno can you add an example service in the examples directory so we can see its usage?

2022-02-03 15:53 UTC, jorge-crespo-cedeno commented
> @jorge-crespo-cedeno can you add an example service in the examples directory so we can see its usage?

Sure. Done

2022-02-03 15:58 UTC, rossnelson approved these changes

2022-02-03 15:58 UTC, rossnelson commented on examples/services/kafka/config.go
> +	IsPrivate:     false,
we can leave these off if they arent used by kafka.

2022-02-03 16:07 UTC, merged